version: '2'
services:
    msa:
        restart: always
        image: 'ms_prospecto_genby_js:PROD_V_0.11'
        env_file: .env.production
        ports:
            - '30014:3000'
        networks:
            - app_mysql_innout_networks

    msb:
        restart: always
        image: 'ms_prospecto_genby_js:PROD_V_0.11'
        env_file: .env.production
        ports:
            - '40014:3000'
        networks:
            - app_mysql_innout_networks

networks:
    app_mysql_innout_networks:
        external: true
